# Generated by Django 6.0 on 2026-06-09 10:15

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100, validators=[users.models.validate_only_letters, django.core.validators.MinLengthValidator(3)])),
                ('class_name', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=20, validators=[users.models.validate_roll_number])),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True, validators=[users.models.validate_only_letters])),
                ('parent_phone', models.CharField(blank=True, max_length=10, null=True, validators=[users.models.validate_indian_mobile])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('phone', models.CharField(blank=True, max_length=10, validators=[users.models.validate_indian_mobile])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_student',
                'ordering': ['class_name', 'roll_number'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100, validators=[users.models.validate_only_letters, django.core.validators.MinLengthValidator(3)])),
                ('subject', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('phone', models.CharField(max_length=10, validators=[users.models.validate_indian_mobile])),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_teacher',
                'ordering': ['full_name'],
            },
        ),
    ]
